version: '3.9'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nova-back-prod
        ports:
            - '3000:3000'
        env_file:
            - .env.prod
