services:
    backend:
        image: node:18
        container_name: projetfin-dev
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3030:3030'
        command: sh -c "npm install && npm run dev"
        env_file:
            - .env.dev
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: projetfin-postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=projetfin_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
